### ISSUE TITLE
 worf-goto VERY slow compared to helm-org-headlines

### ISSUE THREAD

**Issue by zeltak** [abo-abo/worf#12]
Hi!

i find  worf-goto far superior compared to helm-org-headlines in terms of the UI, ease of use etc. i would love to over to use it full time. yet it seems 10x slower than the helm-org-headlines option. on a 40000 line org file (my main note file) it takes around 15-20 seconds just to load...this makes it not very usable :)
is there a way to speed things up? or perhaps use the excellent ivy/swiper to search orgmode headlines only?

thx so much

Z

**Comment by abo-abo** [comment]
Thanks, please check if the speed is better now.

**Comment by zeltak** [comment]
thx! i tried updating from melpa but it seems it hasent been pushed yet, ill keep checking and try it as soon as published :)

thx so much and a happy new years :) 

z

**Comment by zeltak** [comment]
Sweet! beyond amazing, works like a charm now

thx so much!

Z
