### ISSUE TITLE
Allow wspecial-worf-add to add line before heading

### ISSUE THREAD

**Issue by sooheon** [abo-abo/worf#15]
C-return in org respects empty line conventions in your file. Is it possible to let wspecial-worf-add also do this?

```
* foo
* bar|
```

Gives:

```
* foo
* bar
* |
```

and 

```
* foo

* bar|
```

Gives

```
* foo

* bar

* |
```

**Comment by abo-abo** [comment]
I'm not really interested in adding that behavior. But PR welcome.

**Comment by sooheon** [comment]
What do you think about using `org-insert-heading-respect-content` directly? Like this:

    (defun worf-add (arg)
      "Add a new heading below.
    Positive ARG shifts the heading right.
    Negative ARG shifts the heading left."
      (interactive "p")
      (condition-case nil
          (progn
            (forward-char)
            (org-insert-heading-respect-content)
            (worf--ensure-visible))
        (error (org-insert-heading-respect-content)))
      (cond ((> arg 1)
             (worf-dotimes-protect (1- arg)
               (org-metaright)))
            ((cl-minusp arg)
             (worf-dotimes-protect (- arg)
               (org-metaleft))))
      (when worf-keyword-mode
        (insert (worf-mod-keyword) " ")
        (worf-keyword-mode -1)))
