### ISSUE TITLE
cannot input "[" with worf-mode enabled

### ISSUE THREAD

**Issue by seudut** [abo-abo/worf#19]
In worf.el, looks like "[" is mapped to worf-backwar in global map. how can I input "[" in org-mode, not in the header line

**Comment by seudut** [comment]
I just now redefined these two mapping to fix this issue

    (define-key worf-mode-map "[" nil)
    (define-key worf-mode-map "]" nil)
    (define-key worf-mode-map (kbd "M-[") 'worf-backward)
    (define-key worf-mode-map (kbd "M-]") 'worf-forward)

**Comment by abo-abo** [comment]
I use `C-q [` to enter the `[` character. <kbd>C-q</kbd> is a generic way to solve the problem of entering a key that's bound to a command.
