### ISSUE TITLE
[SEVERE BUG] after latest ivy update worf gives error

### ISSUE THREAD

**Issue by zeltak** [abo-abo/worf#20]
Hi worf gives an error when trying to jump to selected header i think since the last ivy update. the error is:
```
ivy-call: Wrong type argument: integer-or-marker-p, (#("2   ivy" 4 7 (pabbrev-added t face org-level-2 org-category "settings" fontified t)) . 59106)
```

i did reintsall both worf and ivy but that didnt seem to help. any clue?

thx

z

**Comment by abo-abo** [comment]
Thanks, should be fixed now.
