### ISSUE TITLE
`worf-change-shift-mode`: "hjkl" or "wasd"?

### ISSUE THREAD

**Issue by Andre0991** [abo-abo/worf#23]
The docs say `hjkl` are used to move headings after activating `worf-change-shift-mode`, but I get this Hydra instead, which uses `wasd` for moving headings:

![screenshot 2016-09-06 15 28 15](https://cloud.githubusercontent.com/assets/7083061/18285859/a43d4f7c-7446-11e6-8435-d92b63e81cef.png)

Are the docs not up do date or am I missing something?

(the docs say "While worf-change-shift-mode is active, hjkl act as S- and arrows in the default org".)

Anyway, to be honest, I would prefer using `hjkl` as it's consistent with the other keybindings. What do you think?

**Comment by Andre0991** [comment]
Unrelated: I think it would be nice to add `worf-backward` to the docs.

**Comment by abo-abo** [comment]
Keys <kbd>w</kbd> and <kbd>s</kbd> are used because <kbd>j</kbd> and <kbd>k</kbd> are still very useful in change mode: e.g. <kbd>jljljl</kbd> or <kbd>wwjjjwwjj</kbd>.

> Unrelated: I think it would be nice to add worf-backward to the docs.

PR welcome.

**Comment by Andre0991** [comment]
OK, that makes sense.

PR: https://github.com/abo-abo/worf/pull/24
