### ISSUE TITLE
Beginning of buffer is treated as special position

### ISSUE THREAD

**Issue by d12frosted** [abo-abo/worf#25]
Hey,

Looks like `worf-mode` treats beginning of buffer as special position, so instead of inserting letters it executes underlying commands.

1. Open any org file or create empty buffer with `org-mode` enabled.
2. Go to beginning of buffer.
3. Type `H`.
4. Notice `Nothing here, move along` in the echo area.

Instead I would like `H` letter to be inserted.

To be honest it would not be such a pain if it's wasn't the same in `org-campture-mode`. In some templates capture buffer is empty and you have to escape via `C-q` first letter you type. I know that it's possible to disable `worf-mode` via `org-capture-mode-hook`, but I find `worf-mode` useful in that mode as well. 

Is such behaviour a bug? Or is it by design? If so, is it possible to change it? 😸 

Thanks in advance.

P. S. Many thanks for this wonderful package!

**Comment by abo-abo** [comment]
> Is such behaviour a bug? Or is it by design? If so, is it possible to change it? :smile_cat:

Yea, it's a bug. I encounter it from time to time and just press <kbd>C-q H</kbd> because I'm lazy.

**Comment by abo-abo** [comment]
I think the original idea was to press <kbd>a</kbd> to insert a heading in a new file. Dumb idea, since <kbd>*</kbd> does the same:)

**Comment by d12frosted** [comment]
Well, hitting `a` is faster for sure. But in some cases I don't want to start org-mode file with heading 😸 Thanks for a fix. I'll take a look once it's on MELPA.
