### ISSUE TITLE
error: (invalid-function with-ivy-window) on latest worf mode

### ISSUE THREAD

**Issue by seudut** [abo-abo/worf#26]
I just updated some of my package as well as `worf-mode` today, then I get this error, when run command `(wspecial-worf-goto)`

here is the error

    Debugger entered--Lisp error: (invalid-function with-ivy-window)
      with-ivy-window(656 nil nil)
      worf-goto-action((#("2   Package Initialization" 0 1 (idx 3) 4 26 (face org-level-2)) . 656))
      ivy-call()
      ....

I google the related error <https://github.com/abo-abo/swiper/issues/185>, then I re-install all the related package, such as `swiper`, `ivy`,  but the issue is still not resolved. 

Any other idea?

Thanks

**Comment by abo-abo** [comment]
You need to recompile and reload `worf.el`. From `dired` with cursor on `worf.el`:

- press <kbd>B</kbd> to recompile.
- press <kbd>L</kbd> to reload.

**Comment by seudut** [comment]
Thank abo-abo for the quick response. After recompiling worf.el, the issue is resolved.

**Comment by abo-abo** [comment]
Great. Feel free to close the issue once it's resolved.
