### ISSUE TITLE
worf-todo increments number in heading

### ISSUE THREAD

**Issue by d12frosted** [abo-abo/worf#27]
Hey,

I have spotted one pretty annoying bug that prevents me from using `worf-todo`. When it's used it increments first number in heading by `1`. Some might not find it critical, but it's critical for me as it changed some important data in my headings without me noticing it. Note that calling `C-c C-t` doesn't change anything in heading except for `TODO` keyword.

* Steps to reproduce

First three steps are options, I just show how exactly I've tested it.

1. Open up Emacs with `-Q` option.
2. Add `org`, `hydra` and `worf` package directories to `load-path` and load them in that exact order. 
3. Open `org-mode` file with following content.

```org-mode
* Heading 1
** TODO Sub-heading 1: say 2
** TODO Sub-heading 2
```

4. Enable `worf-mode` (e. g. `M-: (worf-mode)`).
5. Place cursor at the beginning of second line (`** TODO Sub-heading 1: say 2`).
6. Press `t` and select `d` for `DONE`.

* What happens

The second line changes from ``** TODO Sub-heading 1: say 2`` to ``** DONE Sub-heading 2: say 2`.

* What is expected to happen

The second line changes from ``** TODO Sub-heading 1: say 2`` to ``** DONE Sub-heading 1: say 2` without changing any numbers in text.

---

`Worf` version is `20161206.201`. If you need any more additional information, please let me know.

**Comment by d12frosted** [comment]
Ok, it's seems to be [intentional](https://github.com/abo-abo/worf/blob/master/worf.el#L1208). Could you please explain what purposes this feature has? 😸

**Comment by abo-abo** [comment]
The intention is to automatically track how many times an activity was repeated, e.g. "weekly review 20" turns into "weekly review 21".

**Comment by d12frosted** [comment]
Oh yeah, it makes sense for recurring tasks. Thanks for the quick fix! 👍
