### ISSUE TITLE
[BUG] 100% reproduicable, loading worf disables company-mode completions in orgmode

### ISSUE THREAD

**Issue by zeltak** [abo-abo/worf#28]
Hi

I discovered today that when i enable worf mode it kills/disables company-mode completions in an orgmode buffer.

this is my relevant company mode  config

```
  (use-package company 
   :ensure t
   :config
  (add-hook 'after-init-hook 'global-company-mode)

  (setq company-idle-delay 0)
  (setq company-minimum-prefix-length 2) 
    
(add-to-list 'company-backends 'company-ispell)
(add-to-list 'company-backends 'company-dabbrev)
(add-to-list 'company-backends 'company-abbrev)

)

 (defun my-org-mode-hook ()
      (set (make-local-variable 'company-backends)
           '((company-capf company-files company-dabbrev))))


(add-hook 'org-mode-hook #'my-org-mode-hook)
```

any clue why this happens? can you confirm?  can we try and debug this?

**EDIT: if i move my worf config below company mode it seems to work..strange..any clue why?**

thx alot in advance!

Z

**Comment by abo-abo** [comment]
`worf` needs to be loaded /after/ `company`. Loading `worf` detects if you use `company` and adjusts itself to make company completion work.
