### ISSUE TITLE
worf-backward gets to bolded text instead of headline

### ISSUE THREAD

**Issue by Andre0991** [abo-abo/worf#29]
Hi.

It seems that the regex for getting back to a headline fails when there's a line that contains only bolded text.

For example, consider the following text:

```
*** Headline
*Bolded text*
- Line 1
- Line 2.
```

When the point is on line 2 and `worf-backward` is executed, the point moves to the bolded text instead. The expect behaviour would be getting to the headline, I think.

**Comment by abo-abo** [comment]
Thanks.
