### ISSUE TITLE
~wta~ will NOT add a new heading with *TODO* keyword

### ISSUE THREAD

**Issue by snowman** [abo-abo/worf#40]
> ** ~a~ - added
> :PROPERTIES:
> :CUSTOM_ID: added
> :END:
> Represents /added/ heading. The behavior depends on the currently
> active verb:
> *** goto
> Forward to =org-insert-heading-respect-content= (bound to ~C-RET~ in =org-mode=).
> 
> *** change
> Forward to =org-meta-return= (bound to ~M-RET~ in =org-mode=).
> 
> *** keyword   <--------------- HERE document is not true  ---------------------------------->
> Add a new heading with a corresponding keyword.
> 
> For example ~wta~ will add a new *TODO*, and ~wna~ will add a new
> *NEXT*.

source: [README.org](https://github.com/abo-abo/worf/blob/eda794f6bc9494c9deafade36e9157d5d007de5f/README.org?plain=1#L125-L141)

`wta` would *NOT* add new heading with *TODO* status, instead, it makes the current heading as *TODO* keyword and adds a new heading *without* any keywords.

**Comment by abo-abo** [comment]
Thanks, please test.
