### ISSUE TITLE
is it possible to disable worf bindings when a region is selected

### ISSUE THREAD

**Issue by Lompik** [abo-abo/worf#7]
Or how could I make `worf` work with https://github.com/fgallina/region-bindings-mode ?

**Comment by abo-abo** [comment]
Can you be more concrete? Worf currently does not take over region bindings, although it might in the future.

**Comment by Lompik** [comment]
So I have the key "a" binding whenever I select a region.

 But now when I select a region : 
* with `worf-mode` enabled , `C-h k a` yields `(wspecial-worf-add ARG)`
* with `worf-mode` disabled, `C-h k a` yields `(mc/mark-all-like-this)`

I need the second case with `worf`.Any clue how to tackle this ?

**Comment by abo-abo** [comment]
- `worf-mode` is a minor mode.
- `region-bindings-mode` is a minor mode.

When two minor modes contest a binding, you can use [minor-mode-hack](https://github.com/emacsmirror/minor-mode-hack) to decide which one should get the priority.

**Comment by Lompik** [comment]
thanks
